server :
    port : 12349
eureka :
    client :
        serviceUrl :
             defaultZone: http://localhost:12345/eureka/
feign:
  hystrix:
    enabled: true
spring:
    application :
       name: service-feign
